//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongNet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupClientAndGroupUser
    {
        public string GroupUserName { get; set; }
        public string GroupClientName { get; set; }
        public Nullable<double> GiaDichVu { get; set; }
    
        public virtual GroupClient GroupClient { get; set; }
        public virtual GroupUser GroupUser { get; set; }
    }
}
