//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongNet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginMember
    {
        public int LoginID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public string ClientName { get; set; }
        public Nullable<System.DateTime> LoginDate { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> UseTime { get; set; }
        public Nullable<System.TimeSpan> LeftTime { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Member Member { get; set; }
    }
}
