//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongNet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.LoginMembers = new HashSet<LoginMember>();
            this.TransactionDiary2 = new HashSet<TransactionDiary2>();
        }
    
        public int MemberID { get; set; }
        public string AccountName { get; set; }
        public string Password { get; set; }
        public string GroupUser { get; set; }
        public Nullable<System.TimeSpan> CurrentTime { get; set; }
        public Nullable<double> CurrentMoney { get; set; }
        public string StatusAccount { get; set; }
    
        public virtual GroupUser GroupUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoginMember> LoginMembers { get; set; }
        public virtual MemberInformation MemberInformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionDiary2> TransactionDiary2 { get; set; }
    }
}
