//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongNet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberInformation
    {
        public int MemberID { get; set; }
        public string MemberName { get; set; }
        public Nullable<System.DateTime> FoundedDate { get; set; }
        public string PhoneNumber { get; set; }
        public string MemberAddress { get; set; }
        public string Email { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
