//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongNet.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyPhongNetDB : DbContext
    {
        public QuanLyPhongNetDB()
            : base("name=QuanLyPhongNetDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Drink> Drinks { get; set; }
        public virtual DbSet<Food> Foods { get; set; }
        public virtual DbSet<GroupClient> GroupClients { get; set; }
        public virtual DbSet<GroupClientAndGroupUser> GroupClientAndGroupUsers { get; set; }
        public virtual DbSet<GroupUser> GroupUsers { get; set; }
        public virtual DbSet<LoginMember> LoginMembers { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<MemberInformation> MemberInformations { get; set; }
        public virtual DbSet<OrderCard> OrderCards { get; set; }
        public virtual DbSet<OrderDrink> OrderDrinks { get; set; }
        public virtual DbSet<OrderFood> OrderFoods { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TheCard> TheCards { get; set; }
        public virtual DbSet<TheUser> TheUsers { get; set; }
        public virtual DbSet<TransactionDiary2> TransactionDiary2 { get; set; }
    }
}
