//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongNet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TheUser()
        {
            this.Bills = new HashSet<Bill>();
            this.TransactionDiary2 = new HashSet<TransactionDiary2>();
        }
    
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Type { get; set; }
        public string loginPass { get; set; }
        public string GroupUser { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bills { get; set; }
        public virtual GroupUser GroupUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionDiary2> TransactionDiary2 { get; set; }
    }
}
