//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongNet.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionDiary2
    {
        public int TD_ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<int> memberID { get; set; }
        public Nullable<System.DateTime> TransacDate { get; set; }
        public Nullable<System.TimeSpan> AddTime { get; set; }
        public Nullable<double> AddMoney { get; set; }
        public Nullable<System.TimeSpan> UseTime { get; set; }
        public string Note { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual TheUser TheUser { get; set; }
    }
}
